# Makefile to execute this commands

all:
	clear
	g++ accept.cpp -o myexe
	
run:
	clear
	./myexe $(p1) $(p2)

c:
	clear
	
usage:
	@echo 'use as : make run p1="CommandLine_Argument" p2="CommandLine_Argument"'
	
