# Makefile to execute our program

all:
	clear
	g++ accept.cpp -o myexe
	g++ accept_C2.cpp -o myexe_C2
	g++ accept_C3.cpp -o myexe_C3
	g++ accept_C4.cpp -o myexe_C4
	
run:
	clear
	./myexe

c:
	clear

usage:
	@echo 'use as : make run'
	
