# Makefile to execute our program

all:
	clear
	g++ accept.cpp -o myexe
	
run:
	clear
	./myexe

child:
	g++ accept_Child.cpp -o Child
	./Child

c:
	clear

usage:
	@echo 'use as : make run, for child compilation : make child'
	
