# Makefile to execute our program

all:
	clear
	g++ accept.cpp -o myexe
	g++ accept_C1.cpp -o myexe_C1
	g++ accept_C2.cpp -o myexe_C2
	
run:
	clear
	./myexe

c:
	clear

usage:
	@echo 'use as : make run'
	
